### PR TITLE
remove dependency on List::MoreUtils

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by madsen** [comment]
I'm not sure I see the point of this.  Git::GatherDir still depends on List::MoreUtils via List::AllUtils, so you haven't actually removed a dependency.

**Comment by karenetheridge** [comment]
We have to start somewhere, so I'm trying to patch everything that *can* be patched now, and then do the rest later when List::Util adds some new interfaces.

**Comment by karenetheridge** [comment]
I did miss the use of List::AllUtils as well :) so indeed there isn't a lot of profit in merging this until `uniq` can be ported too, if you want to wait.

**Comment by madsen** [comment]
I went ahead and released it.  I also replaced List::AllUtils with List::MoreUtils, so at least we dropped a dependency on that.

**Comment by karenetheridge** [comment]
..and then, naturally, @shadowcat-mst reminded me of List::UtilsBy this morning, allowing us to do this everywhere:

`sub uniq { unshift @_, sub { $_ }; goto &List::UtilsBy::uniq_by }`

**Comment by madsen** [comment]
I'm not sure that's an improvement, when `uniq` itself is just:

`sub uniq {my %seen; grep { not $seen{$_}++ } @_}`

**Pull request merged**
